# using https://github.com/marketplace/actions/build-and-push-docker-images
# Born-Digital Github Actions for ISLE Releases

name: ci

# For BD only see branches are ISLE-v.*-dev only e.g. ISLE-v.1.5.3-dev
# ISLE branches should only be master and latest
# This will result in the image {{ IMAGE_REPO_ORG }}/isle-tomcat:ISLE-v.1.5.3-dev
on:
  push:
    branches: [ ISLE-v.*-dev ]
  pull_request:
    branches: [ ISLE-v.*-dev ]

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash 
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: borndigital/isle-varnish:1.5.3-dev
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}