# using https://github.com/marketplace/actions/build-and-push-docker-images
# Github Actions for ISLE Releases
# For ISLE Docker Images releases and testing, branches are ISLE-v.*-dev only e.g. ISLE-v.1.5.3-dev or ISLE-v.1.5.3
# ISLE branches should only be master and latest

name: ga-ci

on:
  push:
    branches: [ ISLE-v.* ]
  pull_request:
    branches: [ ISLE-v.* ]

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_ORG }}/isle-varnish:1.5.3
            ${{ secrets.DOCKERHUB_ORG }}/isle-varnish:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}